### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by eldervamp** [CHEF-KOCH/dnscrypt-proxy-blacklist-filter#3]
Hello. Was just wondering if this project is still being maintain. The Blacklist.txt file I see is 5 months old. I seen your other repositories of Host / Domain files are updated and was wondering if you suggest I use those instead. The Blacklist you have here has over 113k entries so I'm sure the list is combined with many others. Are you able to list the sources you used for this blacklist?

**Comment by CHEF-KOCH** [comment]
The project is still maintained.

**Comment by vanyaindigo** [comment]
Hello, is it possible to add some gaming servers in cloaking rules, maybe Valve or EA or PA?
