### ISSUE TITLE
How to use this list?

### ISSUE THREAD

**Issue by jeremyperkin** [CHEF-KOCH/dnscrypt-proxy-blacklist-filter#6]
Hey,

never used lists from others before.  Was wondering if you could provide documentation in the readme for getting started?  
As I have no clue how to use this list you have provided.  Noticed others have python scripts.  Went here to avoid the use of scripts.

**Comment by CHEF-KOCH** [comment]
Hey,
it's already mentioned under [Usage](https://github.com/CHEF-KOCH/dnscrypt-proxy-blacklist-filter#usage) how to us it.

**Comment by jeremyperkin** [comment]
@CHEF-KOCH  I did follow the instructions, downloaded the blacklist.txt list but it does not seem that it is working.   

Should the full path then the file?   Perhaps there is another way that I could test the rules in the blacklist?
