### ISSUE TITLE
Spotify stopped working...

### ISSUE THREAD

**Issue by Skrell** [CHEF-KOCH/dnscrypt-proxy-blacklist-filter#8]
**Describe the problem**
I recently applied your blacklist of domains and now I can browse Spotify but no songs will play.  No clue where to start looking for the domain filter that could be causing it... Any help is greatly appreciated as I love your filter lists and appreciate the hard work you put into them!

**Comment by CHEF-KOCH** [comment]
Please comment out all regular expression rules and report back (_after clearing the dns cache_) if it resolved your issue.
